import fs from "node:fs";import {pages} from "./content.mjs";import {posts} from "./posts.mjs";import {jobs} from "./jobs.mjs";import {pm,pm2,pm3} from "./posts-more.mjs";import {more,more2,more3} from "./more.mjs";
const SITE=(process.env.SITE||"https://YOUR-DOMAIN").replace(/\/$/,""),DATE=new Date().toISOString().slice(0,10),OUT="public";
const E=s=>String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const all=[...pages.map(p=>({...p,url:"/"+p.slug,kind:"page"})),{slug:"blog",url:"/blog",lang:"ar",nav:"المدونة"},{slug:"cv-by-profession",url:"/cv-by-profession",lang:"ar",nav:"سيرة حسب المهنة"}];
const name=l=>l=="en"?"Seerati AI":"سيرتي AI",cta=l=>l=="en"?"Create your resume free":"أنشئ سيرتك الذاتية مجاناً";
const ld=o=>`<script type="application/ld+json">${JSON.stringify(o).replace(/</g,"\\u003c")}</script>`;
const shell=({lang,title,desc,url,body,schema=[],crumbs})=>{const d=lang=="en"?"ltr":"rtl";
return`<!DOCTYPE html><html lang="${lang}" dir="${d}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${E(title)}</title><meta name="description" content="${E(desc)}"><link rel="canonical" href="${SITE}${url}"><meta property="og:type" content="website"><meta property="og:title" content="${E(title)}"><meta property="og:description" content="${E(desc)}"><meta property="og:url" content="${SITE}${url}"><meta property="og:site_name" content="${name(lang)}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${E(title)}"><meta name="twitter:description" content="${E(desc)}"><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/seo.css">${schema.map(ld).join("")}${ld({"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:crumbs.map((c,i)=>({"@type":"ListItem",position:i+1,name:c[0],item:SITE+c[1]}))})}</head><body><header class="sh"><a class="lg" href="/">${name(lang)}</a><a href="/cv-maker">${lang=="en"?"Resume":"إنشاء CV"}</a><a href="/blog">${lang=="en"?"Blog":"المدونة"}</a><a class="btn" href="/#build">${cta(lang)}</a></header><div class="wrap"><main class="sx"><nav aria-label="breadcrumb" class="bc">${crumbs.map((c,i)=>i<crumbs.length-1?`<a href="${c[1]}">${E(c[0])}</a>`:`<span>${E(c[0])}</span>`).join(" › ")}</nav><div data-ad="top"></div>${body}<div data-ad="bottom"></div></main><aside class="ad-side" aria-label="Advertisement"><div data-ad="sidebar"></div></aside></div><footer class="sf"><p>${lang=="en"?"Guidance only; results are not guaranteed.":"الأدوات مساعدة إرشادية ولا تضمن نتيجة."}</p><a href="/privacy">Privacy</a> · <a href="/terms">Terms</a> · <a href="/cookies">Cookies</a> · <a href="#" data-consent-open>Ads settings</a></footer><script src="/config.js" defer></script><script src="/ads.js" defer></script></body></html>`};
const out=(f,h)=>{fs.mkdirSync(OUT+"/"+f.split("/").slice(0,-1).join("/"),{recursive:true});fs.writeFileSync(`${OUT}/${f}`,h)};
const title=(l,k)=>({ar:{b:"المزايا",s:"كيف تعمل",r:"صفحات ذات صلة",f:"الأسئلة الشائعة"},en:{b:"Benefits",s:"How it works",r:"Related",f:"FAQ"}}[l][k]);
for(const p of pages){const l=p.lang,rel=p.links.map(s=>all.find(a=>a.slug==s)).filter(Boolean);
const body=`<h1>${E(p.h1)}</h1><p class="lead">${E(p.intro)}</p><a class="btn" href="/#build">${cta(l)}</a><h2>${title(l,"b")}</h2><ul>${p.benefits.map(b=>`<li>${E(b)}</li>`).join("")}</ul><h2>${title(l,"s")}</h2><ol>${p.steps.map(b=>`<li>${E(b)}</li>`).join("")}</ol><h2>${E(p.extra[0])}</h2><p>${E(p.extra[1])}</p><div data-ad="incontent"></div>${[...(more[p.slug]||[]),...(more2[p.slug]||[]),...(more3[p.slug]||[])].map(m=>`<h2>${E(m[0])}</h2>${Array.isArray(m[1])?`<ul>${m[1].map(x=>`<li>${E(x)}</li>`).join("")}</ul>`:`<p>${E(m[1])}</p>`}`).join("")}<h2>${title(l,"f")}</h2>${p.faq.map(q=>`<details><summary>${E(q[0])}</summary><p>${E(q[1])}</p></details>`).join("")}<h2>${title(l,"r")}</h2><ul>${rel.map(r=>`<li><a href="${r.url}">${E(r.nav)}</a></li>`).join("")}</ul><a class="btn" href="/#build">${cta(l)}</a>`;
const schema=[{"@context":"https://schema.org","@type":"FAQPage",mainEntity:p.faq.map(q=>({"@type":"Question",name:q[0],acceptedAnswer:{"@type":"Answer",text:q[1]}}))}];
if(p.slug=="cv-maker"||p.slug=="resume-builder")schema.push({"@context":"https://schema.org","@type":"WebApplication",name:name(l),url:SITE+"/",applicationCategory:"BusinessApplication",operatingSystem:"Any",offers:{"@type":"Offer",price:"0",priceCurrency:"USD"}});
out(p.slug+".html",shell({lang:l,title:p.title,desc:p.desc,url:"/"+p.slug,body,schema,crumbs:[[name(l),"/"],[p.h1,"/"+p.slug]]}))}
const idx=`<h1>المدونة</h1><p class="lead">مقالات عملية عن السيرة الذاتية والبحث عن وظيفة.</p><ul class="pl">${posts.map(x=>`<li><a href="/blog/${x.slug}"><b>${E(x.title)}</b></a><br><span>${E(x.cat)} — ${E(x.desc)}</span></li>`).join("")}</ul>`;
out("blog.html",shell({lang:"ar",title:"المدونة | سيرتي AI",desc:"مقالات عن السيرة الذاتية وATS ولينكدإن والبحث عن وظيفة.",url:"/blog",body:idx,crumbs:[["سيرتي AI","/"],["المدونة","/blog"]]}));
for(const x of posts){const body=`<h1>${E(x.title)}</h1><p class="note">${E(x.cat)} · ${DATE}</p>`+[...x.body,...(pm[x.slug]||[]),...(pm2[x.slug]||[]),...(pm3[x.slug]||[])].map((b,i)=>(i==2?'<div data-ad="incontent"></div>':"")+(b[0]=="h"?`<h2>${E(b[1])}</h2>`:`<p>${E(b[1])}</p>`)).join("")+`<a class="btn" href="/#build">${cta("ar")}</a><h2>اقرأ أيضاً</h2><ul>${posts.filter(y=>y!=x).slice(0,2).map(y=>`<li><a href="/blog/${y.slug}">${E(y.title)}</a></li>`).join("")}<li><a href="/cv-maker">إنشاء CV</a></li></ul>`;
out(`blog/${x.slug}.html`,shell({lang:"ar",title:x.title+" | سيرتي AI",desc:x.desc,url:"/blog/"+x.slug,body,schema:[{"@context":"https://schema.org","@type":"Article",headline:x.title,datePublished:DATE,inLanguage:"ar",author:{"@type":"Organization",name:"سيرتي AI"}}],crumbs:[["سيرتي AI","/"],["المدونة","/blog"],[x.title,"/blog/"+x.slug]]}))}

const HUBC=[["سيرتي AI","/"],["سيرة حسب المهنة","/cv-by-profession"]];
out("cv-by-profession.html",shell({lang:"ar",title:"نماذج سيرة ذاتية حسب المهنة | سيرتي AI",desc:"اختر مهنتك لترى ما تبرزه في سيرتك، وقوالب نقاط خبرة، وأخطاء شائعة خاصة بها.",url:"/cv-by-profession",crumbs:HUBC,
body:`<h1>سيرة ذاتية حسب المهنة</h1><p class="lead">لكل مهنة ما يُبرز فيها وما يُتجنَّب. اختر مهنتك لترى التفاصيل.</p><ul class="pl">${jobs.map(j=>`<li><a href="/${j.slug}"><b>${E(j.h1)}</b></a><br><span>${E(j.desc)}</span></li>`).join("")}</ul><a class="btn" href="/#build">${cta("ar")}</a>`}));
for(const j of jobs){const rel=jobs.filter(x=>x!==j).slice(0,3);
const body=`<h1>${E(j.h1)}</h1><p class="lead">${E(j.intro)}</p><a class="btn" href="/#build">${cta("ar")}</a><h2>ما الذي تُبرزه؟</h2><ul>${j.focus.map(b=>`<li>${E(b)}</li>`).join("")}</ul><h2>قوالب نقاط الخبرة</h2><p>املأ الأقواس ببياناتك الحقيقية فقط، واحذف النقطة إن لم تنطبق عليك.</p><ul>${j.bullets.map(b=>`<li>${E(b)}</li>`).join("")}</ul><div data-ad="incontent"></div><h2>نموذج ملخص مهني (قالب)</h2><p>${E(j.summary)}</p><p class="note">عدّله ببياناتك الحقيقية فقط.</p><h2>إن كانت خبرتك قليلة</h2><p>${E(j.entry)}</p><h2>كلمات تتكرر في إعلانات هذه المهنة</h2><p>${j.keywords.map(k=>`<span class="chip">${E(k)}</span>`).join(" ")}</p><p class="note">هذه أمثلة شائعة وليست قائمة إلزامية. اقرأ إعلان الوظيفة التي تتقدم لها، واستخدم ما ينطبق عليك فعلاً.</p><h2>أخطاء شائعة</h2><ul>${j.mistakes.map(b=>`<li>${E(b)}</li>`).join("")}</ul><h2>الأسئلة الشائعة</h2>${j.faq.map(q=>`<details><summary>${E(q[0])}</summary><p>${E(q[1])}</p></details>`).join("")}<h2>صفحات ذات صلة</h2><ul>${rel.map(r=>`<li><a href="/${r.slug}">${E(r.h1)}</a></li>`).join("")}<li><a href="/ats-resume">سيرة ATS</a></li><li><a href="/cv-by-profession">كل المهن</a></li></ul><a class="btn" href="/#build">${cta("ar")}</a>`;
out(j.slug+".html",shell({lang:"ar",title:j.title,desc:j.desc,url:"/"+j.slug,body,crumbs:[...HUBC,[j.h1,"/"+j.slug]],schema:[{"@context":"https://schema.org","@type":"FAQPage",mainEntity:j.faq.map(q=>({"@type":"Question",name:q[0],acceptedAnswer:{"@type":"Answer",text:q[1]}}))}]}))}
const urls=["/",...new Set(all.map(a=>a.url)),...jobs.map(j=>"/"+j.slug),...posts.map(x=>"/blog/"+x.slug),"/privacy","/terms","/cookies"];
out("sitemap.xml",`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(u=>`<url><loc>${SITE}${u}</loc><lastmod>${DATE}</lastmod></url>`).join("\n")}\n</urlset>\n`);
out("robots.txt",`User-agent: *\nAllow: /\nSitemap: ${SITE}/sitemap.xml\n`);
const SB=process.env.API_ORIGIN?" "+process.env.API_ORIGIN:"";const ts=process.env.TURNSTILE==="1",T1=ts?" https://challenges.cloudflare.com":"";const ads=process.env.ADS==="1",G=ads?" https://pagead2.googlesyndication.com https://*.googlesyndication.com https://*.doubleclick.net https://www.googletagservices.com https://adservice.google.com":"";
out("_headers",`/*\n  Strict-Transport-Security: max-age=31536000; includeSubDomains\n  X-Content-Type-Options: nosniff\n  X-Frame-Options: DENY\n  Referrer-Policy: strict-origin-when-cross-origin\n  Permissions-Policy: camera=(), microphone=(), geolocation=()\n  Content-Security-Policy: default-src 'self'; script-src 'self'${G}${T1}; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; img-src 'self' data:${ads?" https:":""}; connect-src 'self'${SB}${G}; frame-src ${(ads||ts)?[ads?"https://googleads.g.doubleclick.net https://*.googlesyndication.com":"",ts?"https://challenges.cloudflare.com":""].join(" ").trim():"'none'"}; frame-ancestors 'none'; base-uri 'self'; form-action 'self'\n`);
console.log("built",urls.length,"urls for",SITE);
