export const pages=[
{slug:"cv-maker",lang:"ar",nav:"إنشاء CV",title:"إنشاء CV مجاني بالذكاء الاصطناعي | سيرتي AI",desc:"أنشئ CV احترافي بالعربية أو الإنجليزية: اكتب خبراتك، أضف الوصف الوظيفي، ودع الذكاء الاصطناعي يصوغ سيرتك ويحلل توافقها مع ATS.",
h1:"إنشاء CV احترافي بالذكاء الاصطناعي",
intro:"تبدأ بإدخال بياناتك الحقيقية: التعليم والخبرات والمهارات. بعدها تضيف الوظيفة التي تتقدم لها، فيعيد الذكاء الاصطناعي صياغة خبراتك بأفعال قوية ولغة مهنية واضحة، دون أن يضيف وظيفة أو شهادة أو رقماً لم تذكره. النتيجة مسودة تراجعها وتعدّلها بنفسك قبل الإرسال.",
benefits:["صياغة مهنية للخبرات مع إبراز النتائج الرقمية التي تقدمها أنت فقط","أربعة قوالب تدعم العربية RTL والإنجليزية LTR وتُطبع على A4","تحليل إرشادي للكلمات المفتاحية المطابقة والناقصة مقارنة بالوصف الوظيفي","تعديل كل قسم مع تراجع وإعادة، ثم نسخ أو طباعة أو تنزيل"],
steps:["أدخل بياناتك الشخصية وخبراتك وتعليمك ومهاراتك.","الصق الوصف الوظيفي للوظيفة المستهدفة.","اضغط إنشاء، ثم راجع النتيجة وعدّلها.","اختر القالب وانسخ سيرتك أو اطبعها أو نزّلها."],
extra:["متى يكون إنشاء CV بالذكاء الاصطناعي مفيداً؟","يفيدك عندما تعرف خبراتك لكن تجد صعوبة في صياغتها، أو عندما تقدّم على وظائف مختلفة وتحتاج تعديل السيرة لكل وظيفة. أما إن كانت بياناتك قليلة جداً فستحصل على سيرة قصيرة، وهذا أفضل من سيرة مليئة بمعلومات غير حقيقية."],
faq:[["هل الخدمة مجانية؟","الاستخدام الأساسي مجاني حالياً، وقد تُضاف مزايا مدفوعة مستقبلاً دون إلغاء الأدوات الأساسية."],["هل يخترع الذكاء الاصطناعي خبرات؟","لا، التعليمات تمنعه من ذلك، لكن راجع كل سطر لأنك المسؤول عن دقة سيرتك."],["أين تُحفظ بياناتي؟","في متصفحك. وتُرسل إلى مزوّد الذكاء الاصطناعي فقط عند الضغط على زر التوليد."]],
links:["ats-resume","resume-templates","cover-letter","cv-by-profession"]},
{slug:"resume-builder",lang:"en",nav:"Resume Builder",title:"AI Resume Builder in Arabic & English | Seerati AI",desc:"Build a clean, ATS-friendly resume in Arabic or English. Add your experience and a job description, then edit, print or download.",
h1:"AI Resume Builder for Arabic and English Resumes",
intro:"Seerati AI turns your raw experience into a structured resume. Enter what you have done, paste the job you want, and the AI rewrites your bullet points in clear business English or Modern Standard Arabic. It is instructed to use only the facts you provide, so you stay in control of what your resume claims.",
benefits:["Bilingual output with correct right-to-left layout for Arabic","Four print-ready A4 templates, including a minimal ATS layout","Keyword match and gap analysis against a job description","Section-level editing with undo, redo, shorten, expand and translate"],
steps:["Fill in your details step by step.","Paste the target job description.","Generate, then review every line.","Pick a template and export."],
extra:["Who is it for?","Job seekers who apply in both Arabic and English markets, graduates writing a first resume, and professionals tailoring one profile to several roles. If you only need a simple template, the minimal layout works without any AI at all."],
faq:[["Is it free?","The core tools are free for now."],["Will it make up experience?","It is told not to, but always verify the result."],["Can I use Arabic and English?","Yes, switch language at any time."]],
links:["ats-friendly-resume","cv-maker-arabic","cover-letter","resume-templates"]},
{slug:"ats-resume",lang:"ar",nav:"سيرة ATS",title:"سيرة ذاتية ATS: كيف تكتبها وتفحصها | سيرتي AI",desc:"افهم أنظمة تتبع المتقدمين ATS، واكتب سيرة ذاتية بسيطة وواضحة، وافحص الكلمات المفتاحية الناقصة مقارنة بالوصف الوظيفي.",
h1:"سيرة ذاتية متوافقة مع أنظمة ATS",
intro:"أنظمة تتبع المتقدمين تقرأ ملف سيرتك كنص وتحاول تصنيف الأقسام والخبرات. كلما كان التنسيق بسيطاً والعناوين معروفة، زادت فرصة قراءتها بشكل سليم. لا يوجد نظام يضمن لك القبول، لكن تجنب الأخطاء الشائعة يساعدك.",
benefits:["عناوين أقسام قياسية: ملخص، خبرات، تعليم، مهارات","بدون جداول معقدة أو صور أو أعمدة تربك القراءة","كلمات مفتاحية مأخوذة من الوصف الوظيفي عندما تنطبق عليك فعلاً","نقاط مختصرة تبدأ بفعل وتحتوي على نتيجة"],
steps:["الصق الوصف الوظيفي واضغط تحليل.","قارن الكلمات المطابقة والناقصة.","أضف فقط ما تملكه من مهارات وخبرات حقيقية.","اختر قالب ATS البسيط وصدّر السيرة."],
extra:["كيف تُحسب النسبة في سيرتي AI؟","النسبة تقديرية وتُحسب من خمسة معايير معلنة: الكلمات المفتاحية (45%)، مطابقة المسمى (15%)، هيكل الأقسام (15%)، بيانات التواصل (10%)، ووضوح الصياغة (15%). هي تحليل إرشادي مبني على النص والوصف الوظيفي، ولا يضمن اجتياز أي نظام ATS محدد."],
faq:[["هل تضمن المنصة قبولي في ATS؟","لا، التحليل إرشادي فقط."],["هل أضيف كل الكلمات الناقصة؟","فقط ما ينطبق عليك فعلاً، وإلا ستظهر في المقابلة فجوة بين سيرتك وواقعك."],["أي قالب أختار؟","قالب ATS البسيط هو الأنسب للتقديم عبر المواقع."]],
links:["ats-friendly-resume","cv-maker","resume-templates","blog"]},
{slug:"cover-letter",lang:"ar",nav:"رسالة تقديم",title:"إنشاء رسالة تقديم Cover Letter بالعربية والإنجليزية | سيرتي AI",desc:"اكتب رسالة تقديم طبيعية وغير مبالغ فيها تعتمد على خبراتك والوصف الوظيفي، ثم عدّلها وانسخها.",
h1:"إنشاء رسالة تقديم احترافية",
intro:"رسالة التقديم فرصة قصيرة لتشرح لماذا أنت مناسب لهذه الوظيفة بالذات. تستخدم الأداة اسمك وخبراتك ومهاراتك والوصف الوظيفي واسم الشركة الذي تكتبه، وتنتج رسالة أقل من 300 كلمة بفقرات واضحة.",
benefits:["لهجة مهنية طبيعية دون مبالغة","لا تُختلق معلومات عن الشركة؛ تُستخدم فقط المعلومات التي تكتبها","رسالة قابلة للتعديل والنسخ بنقرة","تدعم العربية والإنجليزية"],
steps:["أكمل بياناتك وخبراتك أولاً.","اكتب اسم الشركة والصق الوصف الوظيفي.","اضغط إنشاء رسالة التقديم.","عدّل الأمثلة والنبرة لتشبهك."],
extra:["ما الذي يجعل الرسالة جيدة؟","ابدأ بالوظيفة التي تتقدم لها، واذكر إنجازاً أو اثنين مرتبطين بمتطلباتها، واختم بطلب مقابلة. أضف بنفسك سبب اهتمامك بالشركة إن كان لديك سبب حقيقي، فهذا ما لا تستطيع الأداة معرفته."],
faq:[["هل أحتاج رسالة لكل وظيفة؟","الأفضل تخصيصها، ولو بتغيير الفقرة الأولى والأمثلة."],["كم يجب أن يكون طولها؟","صفحة واحدة أو أقل."],["هل يعرف الذكاء الاصطناعي شيئاً عن شركتي المستهدفة؟","لا، إلا ما تكتبه أنت."]],
links:["cv-maker","linkedin-summary","ats-resume","blog"]},
{slug:"linkedin-summary",lang:"ar",nav:"ملخص لينكدإن",title:"ملخص لينكدإن About احترافي بالذكاء الاصطناعي | سيرتي AI",desc:"أنشئ ثلاث نسخ لقسم About في لينكدإن: احترافية ومختصرة ومناسبة للبحث بالكلمات المفتاحية.",
h1:"إنشاء ملخص لينكدإن (About)",
intro:"قسم About هو أول ما يقرؤه المسؤول عن التوظيف بعد اسمك ومسماك. تُنشئ الأداة ثلاث نسخ من بياناتك الحقيقية لتختار ما يناسب هدفك.",
benefits:["نسخة احترافية حتى 200 كلمة","نسخة مختصرة حتى 60 كلمة","نسخة غنية بالكلمات المفتاحية للظهور في البحث","نسخ بنقرة واحدة"],
steps:["أدخل بياناتك في منشئ السيرة.","افتح صفحة لينكدإن واضغط إنشاء.","اختر النسخة المناسبة وعدّلها.","الصقها في ملفك."],
extra:["نصيحة للبحث","يبحث المسؤولون عن التوظيف بالمسمى والمهارات. اكتب مسماك المعتاد في السوق مرة واحدة في بداية الملخص، وذكر أدواتك الأساسية بشكل طبيعي بدل حشوها."],
faq:[["أي نسخة أختار؟","الاحترافية للملف الكامل، والمختصرة للسير القصيرة، والكلمات المفتاحية لمن يبحث عن فرص."],["هل أنشر النص كما هو؟","راجعه وعدّله ليعكس صوتك."],["هل تربط الأداة حسابي في لينكدإن؟","لا، تنسخ النص وتلصقه بنفسك."]],
links:["cover-letter","cv-maker","blog"]},
{slug:"resume-templates",lang:"ar",nav:"القوالب",title:"قوالب سيرة ذاتية: كلاسيكي وحديث وATS | سيرتي AI",desc:"أربعة قوالب CV بحجم A4 تدعم العربية والإنجليزية: كلاسيكي، حديث، وATS بسيط. تعرّف على الفرق ومتى تستخدم كل قالب.",
h1:"قوالب السيرة الذاتية",
intro:"القالب يغيّر الشكل فقط، أما محتوى سيرتك فيبقى كما هو. لذلك يمكنك تبديل القالب في أي وقت دون إعادة الإنشاء.",
benefits:["كلاسيكي Professional: عناوين مركزية وخطوط فاصلة، مناسب لمعظم الوظائف","حديث Modern: لمسة لونية وعناوين جانبية، مناسب للتقنية والشركات الناشئة","ATS بسيط Minimal: بلا زخرفة، الأنسب للتقديم عبر مواقع التوظيف","مدمج Compact: خط أصغر ومسافات أقل للسير الطويلة","جميعها تُطبع على A4 وتحافظ على اتجاه RTL أو LTR"],
steps:["أنشئ سيرتك أولاً.","جرّب القوالب الأربعة من شاشة النتيجة.","اختر حسب الجهة التي ستقدّم إليها.","اطبع أو نزّل."],
extra:["كيف أختار؟","إن كنت ترسل السيرة عبر نموذج على موقع أو بريد لقسم الموارد البشرية فالأفضل قالب ATS البسيط. وإن كنت تسلّمها يداً بيد أو تشاركها كملف مع شخص فالكلاسيكي أو الحديث مناسبان."],
faq:[["هل تغيير القالب يحذف تعديلاتي؟","لا."],["هل توجد قوالب مدفوعة؟","لا حالياً."],["هل القوالب تدعم الطباعة؟","نعم، بحجم A4."]],
links:["cv-maker","ats-resume","free-cv-template"]},
{slug:"free-cv-template",lang:"ar",nav:"نموذج سيرة ذاتية",title:"نموذج سيرة ذاتية جاهزة مجاناً للتعديل | سيرتي AI",desc:"نموذج سيرة ذاتية جاهزة تملؤها ببياناتك وتطبعها: أقسامها، مثال على صياغة الخبرات، وأخطاء يجب تجنبها.",
h1:"نموذج سيرة ذاتية جاهزة",
intro:"بدل البدء من صفحة فارغة، املأ النموذج خطوة بخطوة. الترتيب الذي تعتمده الأداة: البيانات الشخصية، ملخص، خبرات، تعليم، مهارات، شهادات، مشاريع، لغات.",
benefits:["ترتيب أقسام معتمد وسهل القراءة","حقول واضحة لكل خبرة وتعليم","معاينة فورية أثناء التعديل","تقدر تستخدمه بدون الذكاء الاصطناعي عبر زر المعاينة"],
steps:["افتح منشئ السيرة.","املأ الحقول الأساسية.","اختر معاينة بدون AI إن أردت.","اطبع."],
extra:["مثال على نقطة خبرة جيدة","بدلاً من «مسؤول عن المبيعات» اكتب «أدرت حسابات 15 عميلاً وأغلقت صفقات بقيمة كذا» بشرط أن يكون الرقم حقيقياً. ابدأ بفعل، واذكر ما فعلته ونتيجته."],
faq:[["هل أحتاج صورة؟","في كثير من الأسواق لا، وهي غير مطلوبة في قوالب ATS."],["كم صفحة؟","صفحة واحدة للمبتدئ، وحتى صفحتين لصاحب الخبرة."],["هل أكتب الراتب؟","لا، إلا إذا طُلب ذلك صراحة."]],
links:["cv-maker","resume-templates","cv-maker-english"]},
{slug:"ats-friendly-resume",lang:"en",nav:"ATS-friendly",title:"ATS-Friendly Resume: Rules and a Free Keyword Check | Seerati AI",desc:"What makes a resume ATS-friendly: simple structure, standard headings, real keywords. Check matched and missing keywords against a job description.",
h1:"How to Write an ATS-Friendly Resume",
intro:"Applicant tracking systems parse your resume into fields before a person reads it. Clean structure helps that parsing. No tool can promise a pass, but avoiding common formatting mistakes removes avoidable risk.",
benefits:["Standard headings: Summary, Experience, Education, Skills","Single column, no tables, icons or text inside images","Keywords from the job description, only where they are true for you","Bullets that start with a verb and show a result"],
steps:["Paste the job description and run the analyzer.","Compare matched and missing keywords.","Edit your resume honestly.","Export with the Minimal ATS template."],
extra:["What our score means","The percentage is a rough guide from five published criteria: keywords, title match, section structure, contact details and readability. It does not guarantee that any specific ATS will accept your resume."],
faq:[["Do I need exact keywords?","Use the wording of the job where it is accurate for you."],["Is a PDF safe?","A text-based PDF is usually fine; avoid scanned images."],["Does the score guarantee anything?","No, it is guidance only."]],
links:["ats-resume","resume-builder","cv-maker-arabic"]},
{slug:"cv-maker-arabic",lang:"ar",nav:"CV عربي",title:"نموذج CV عربي RTL يُطبع بشكل صحيح | سيرتي AI",desc:"أنشئ سيرة ذاتية بالعربية مع اتجاه RTL صحيح، مع بقاء أسماء الأدوات والشركات الأجنبية مقروءة.",
h1:"إنشاء سيرة ذاتية عربية بتنسيق RTL صحيح",
intro:"أغلب مشاكل السيرة العربية تأتي من التنسيق: أرقام وتواريخ تنقلب، وأسماء شركات إنجليزية تتشوش، وأقسام تظهر على الجهة الخطأ. القوالب هنا مبنية على اتجاه RTL فعلاً وتختبر هذه الحالات.",
benefits:["عناوين وفقرات من اليمين لليسار","التواريخ وروابط التواصل تبقى بالاتجاه الصحيح","مصطلحات مثل Python وCybersecurity تبقى بالإنجليزية لسهولة البحث","طباعة A4 تحافظ على الاتجاه"],
steps:["اختر العربية من زر اللغة.","اكتب بياناتك كما تشاء.","أنشئ واختر قالباً.","تأكد من التواريخ قبل الطباعة."],
extra:["هل أكتب الأدوات بالعربية أم الإنجليزية؟","اكتب أسماء التقنيات والبرامج بالإنجليزية كما يبحث عنها أصحاب العمل، وشرح الدور بالعربية. أنظمة ATS غالباً تبحث بالكلمة الإنجليزية المعتادة."],
faq:[["هل أرسل سيرة عربية لشركة دولية؟","الأفضل سيرة إنجليزية؛ العربية للوظائف المحلية."],["هل يمكن الجمع؟","أنشئ نسختين من نفس البيانات."],["هل الأرقام هندية أم عربية؟","استخدم ما يناسب الجهة المستقبلة، والأرقام الغربية أكثر أماناً مع ATS."]],
links:["cv-maker-english","cv-maker","ats-resume"]},
{slug:"cv-maker-english",lang:"ar",nav:"CV إنجليزي",title:"إنشاء CV باللغة الإنجليزية للعرب | سيرتي AI",desc:"اكتب بياناتك بالعربية أو الإنجليزية وأنشئ سيرة ذاتية بإنجليزية مهنية بسيطة للتقديم على وظائف دولية.",
h1:"إنشاء CV باللغة الإنجليزية",
intro:"تقديمك لوظيفة دولية يتطلب سيرة بإنجليزية مهنية واضحة. اكتب خبراتك بأي لغة تجيدها، واطلب من الأداة صياغتها بإنجليزية بسيطة وجمل قصيرة وأفعال مناسبة.",
benefits:["إنجليزية مهنية بدون حشو","أفعال مثل Led وBuilt وImproved تبدأ بها النقاط","ترجمة قسم واحد بزر Translate","قالب ATS مناسب للشركات الدولية"],
steps:["بدّل اللغة إلى English.","أدخل بياناتك.","أنشئ وراجع الصياغة.","استخدم Translate لأي قسم كتبته بالعربية."],
extra:["راجع الترجمة","الترجمة الآلية قد تغيّر معنى مصطلحاً مهنياً. اقرأ الناتج أو اطلب من زميل يجيد الإنجليزية مراجعته قبل الإرسال."],
faq:[["هل أكتب بالعربية أولاً؟","نعم، يمكنك ذلك ثم تترجم."],["هل يغير الذكاء الاصطناعي الحقائق؟","لا يجب ذلك، لكن راجع الأرقام والتواريخ."],["أي قالب أختار؟","Minimal ATS للتقديم الإلكتروني."]],
links:["resume-builder","cv-maker-arabic","cover-letter"]}
];
